import { createSyncAdapter } from "./types.js"
import { renderRulesSections } from "./rules-render.js"

export const windsurf = createSyncAdapter("windsurf", ".windsurfrules", (ctx) => {
  const header = [
    "---",
    `name: ${ctx.projectName ?? "project"}-rules`,
    "description: Auto-generated by agentmind — do not edit manually",
    "ruleFormat: natural",
    "---",
    "",
    "# Run `agentmind sync --tool windsurf` to update",
    "",
  ].join("\n")

  return header + renderRulesSections(ctx)
})
