import { createSyncAdapter } from "./types.js"

export const windsurf = createSyncAdapter("windsurf", ".windsurfrules", (ctx) => {
  const lines: string[] = []

  lines.push("---")
  lines.push(`name: ${ctx.projectName ?? "project"}-rules`)
  lines.push("description: Auto-generated by agentmind — do not edit manually")
  lines.push("ruleFormat: natural")
  lines.push("---")
  lines.push("")
  lines.push("# Run `agentmind sync --tool windsurf` to update")
  lines.push("")

  const withRules = ctx.entries.filter(e => e.rules.length > 0)
  if (withRules.length > 0) {
    lines.push("## Rules")
    lines.push("")
    for (const entry of withRules) {
      for (const rule of entry.rules) {
        const source = rule.path ? `${rule.path}: ` : ""
        lines.push(`- ${source}${rule.description}`)
      }
    }
    lines.push("")
  }

  const annotations = ctx.entries.flatMap(e => e.annotations)
  if (annotations.length > 0) {
    lines.push("## Annotations")
    lines.push("")
    for (const ann of annotations) {
      const loc = ann.line ? `:${ann.line}` : ""
      lines.push(`- ${ann.path}${loc}: ${ann.text}`)
    }
    lines.push("")
  }

  if (ctx.patterns.length > 0) {
    lines.push("## Non-obvious patterns")
    lines.push("")
    for (const p of ctx.patterns) {
      lines.push(`- ${p.path}: ${p.reason}`)
    }
    lines.push("")
  }

  return lines.join("\n")
})
